apiVersion: v1
kind: ReplicationController
metadata:
  name: jmeter-deployment
spec:
  replicas: 1
  selector:
    app: jmeter-deployment
  template:
    metadata:
      name: jmeter-deployment
      labels:
        app: jmeter-deployment
    spec:
      containers:
      - name: jmeter-deployment
        image: harbor.dcos.guangzhou.unicom.local/jmeter/jmeter:latest
        args:
        - -n
        - -t /mnt/jmeter/test.jmx
        - -l /mnt/jmeter/test.jtl
        - -e
        - -o /mnt/jmeter/index
        volumeMounts:
        - name: jmeter
          mountPath: /mnt/
      volumes:
      - name: jmeter
        persistentVolumeClaim:
          claimName: jmeter-pvc