[program:mysqld]
#command=/usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql log-error=/var/log/mysqld.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/lib/mysql/mysql.sock -u root 
command=/usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql  --user=mysql --log-error=/var/log/mysqld.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/lib/mysql/mysql.sock 
user=mysql
autostart = true
autorestart = true
startsecs = 3
startretries = 3
user = root
